# Generated by Django 4.1.4 on 2022-12-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_headline_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
